name: Build rakesh

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can use `ubuntu-latest` if you don't have a self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Maven Build
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Maven
        run: |
          mvn test package
          echo "Maven build and tests complete."

      - name: List build directory contents
        run: |
          echo "Listing the build directory contents..."
          ls -R $(pwd)

      - name: Set version and update version.txt
        run: |
          # Ensure the version.txt file exists; if not, create it with a default version
          if [ ! -f version.txt ]; then
              echo "1.0.1" > version.txt
          fi

          # Read the current version from version.txt
          VERSION_NUMBER=$(cat version.txt)
          
          # Increment the patch version
          IFS='.' read -r major minor patch <<< "$VERSION_NUMBER"
          patch=$((patch + 1))
          NEW_VERSION="${major}.${minor}.${patch}"
          
          # Save the new version back to version.txt
          echo $NEW_VERSION > version.txt
          
          # Use the new version for Docker tagging
          echo "Using version: $NEW_VERSION"
          echo "New version saved in version.txt: $NEW_VERSION"
        shell: bash

      - name: Login to AWS ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 160885281963.dkr.ecr.us-east-1.amazonaws.com

      - name: Build, tag, and push Docker image
        run: |
          docker build -t rakeshecr .
          docker tag rakeshecr:latest 160885281963.dkr.ecr.us-east-1.amazonaws.com/rakeshecr:latest
          docker push 160885281963.dkr.ecr.us-east-1.amazonaws.com/rakeshecr:latest

          
