name: Build and Deploy to EKS

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          mvn test package
          echo "Maven build and tests complete."

      - name: Login to AWS ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 825765405225.dkr.ecr.us-east-1.amazonaws.com

      - name: Build, tag, and push Docker image
        run: |
          docker build -t rakeshecr .
          docker tag rakeshecr:latest 825765405225.dkr.ecr.us-east-1.amazonaws.com/rakeshecr:latest
          docker push 825765405225.dkr.ecr.us-east-1.amazonaws.com/rakeshecr:latest

      - name: Set up KUBECONFIG
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Check kubectl context
        run: |
          kubectl config get-contexts
          kubectl config current-context

      - name: Deploy to EKS
        run: |
          kubectl apply -f deployment.yaml --validate=false

                - name: Set up KUBECONFIG

          mkdir -p ~/.kube
          echo "***" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config
